### ISSUE TITLE
When you import a deck, Anki will manually reschedule the imported cards as new. Review Heatmap erroneously counts these "reschedulings" as reviews

### ISSUE THREAD

**Issue by failingtolearn** [glutanimate/review-heatmap#108]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

**When you import a deck, Anki will manually reschedule the imported cards as new. Review Heatmap erroneously counts these "reschedulings" as reviews. Anki Desktop made a change that additional activities now go into the "review history" database, and the heatmap is picking up on these.**

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by losthero15** [comment]
I believe I have the same question. Lately, I'm rebuilding my decks. So I'm importing a lot of premade decks. Didn't have an issue until yesterday. This addon shows my yesterday's review count over 16k. While it was somewhere around 800. It would be nice to be able to set a upper limit for a day because of this error.

**Comment by glutanimate** [comment]
Thanks for the report, guys. It looks like this is a new feature in Anki 2.1.41. Will look into it, but as 2.1.41 broke a lot of add-ons, it might take me a bit of time to get to this.

**Comment by itsdomme** [comment]
In my case it also appears in 2.1.40 after rescheduling cards in an interval. Anki's stats don't count those cards, but the heatmap does.

**Comment by glutanimate** [comment]
Hey everyone,

Thanks again for the reports! This should be fixed with v1.0.0 which I just released [on AnkiWeb](https://ankiweb.net/shared/info/1771074083) (no need for a manual installation any more, you can just copy the add-on code into Anki as with other add-ons.).

Whether reschedules are included in the heatmap and stats is now configurable via an option under the "Fine Tuning" tab in the add-on's settings menu. It should be enabled by default, so if you had any overly high repetition counts due to manually forgetting/rescheduling cards, they should be corrected for those days

If you run into any issues please do let me know!
