### ISSUE TITLE
Investigate potential issues with Anki's rescheduling function in 2.1.41+

### ISSUE THREAD

**Issue by glutanimate** [glutanimate/review-heatmap#111]
Cards rescheduled via Anki's new rescheduler might be counted as reviews in the heatmap at the moment, as reported here for instance: https://reddit.com/r/Anki/comments/mbgb6u/review_heatmap_counts_reviews_when_using_set_due/

The more desirable behavior would be to ignore rescheduling entries in the review log (if they can be identified as such). Will have to look into the new rescheduling code to see if that's the case.

**Comment by glutanimate** [comment]
Likely related to #108. Both issues might be fixable with at the same time.

**Comment by mindel** [comment]
Please consider not removing completely the current behavior (maybe choosing in the config).
I just love using the new reschedule feature, and setting whatever new interval I need (instead of using anki's algorithm) but keeping track of my "reviews" in your add-on.

**Comment by u2m4c6** [comment]
@glutanimate do you think this bug is something inherit with how the heatmap calculates reviews or a more minor fix? I will start to look into this. The correct stats (unaffected by rescheduling) calculated by the base Anki code seem to be tied into the Rust back end. I am not familiar with Rust, so if anyone who works with Rust would like to take a look at this it would be much appreciated.

**Comment by tsmgodoi** [comment]
In version 2.1.41+, reviews made through a filtered deck are not tracked by the plugin anymore.
