### ISSUE TITLE
When I hover on the square, it does not show date

### ISSUE THREAD

**Issue by sovernut** [glutanimate/review-heatmap#12]
when I hover on the square, it does not show date and total reviews on that day.

**Comment by glutanimate** [comment]
Thanks for the report. Which operating system and Anki version are you using? Do other tooltips (the small labels that appear when hovering over stuff) work? For instance, what happens if you hover your mouse over the statistics icon or the sync icon (top right area of Anki's main interface).

**Comment by sovernut** [comment]
I used Windows 10 Education and Anki 2.0.48 Alternate Version +
Yes, it works.

**Comment by glutanimate** [comment]
Hi @sovernut,
It's been a while since my last message. Sorry about that! I didn't have a lot of time to work on the add-on when we last talked, but I have started on a new version of Review Heatmap recently and I'm going through some older bug reports as part of that.

I just wanted to ask you if you were still experiencing the issue with the tooltips. If so, is there any chance you could attach a screenshot or ideally a GIF showing this action? I haven't been able to reproduce the issue on my Windows test machine so far, and a GIF in particular would really help.

**Comment by glutanimate** [comment]
Sorry, closed the issue by accident.

**Comment by sovernut** [comment]
right now i'm using Anki 2.1
Does Review heatmap support 2.1 ? I cant find it on [add-on page](https://ankiweb.net/shared/addons/2.1)

**Comment by glutanimate** [comment]
Not yet. I'm working on the 2.1 release right now. If you'd like, I could send you a heads-up when the beta version is ready. If you then could check whether the tooltips work for you with that, I'd really appreciate it.

**Comment by sovernut** [comment]
Yes I would like 👍
