### ISSUE TITLE
Option to exclude "forgetting cards" from review count

### ISSUE THREAD

**Issue by Qaspar** [glutanimate/review-heatmap#122]
I've been doing major overhauls of my decks and in the process I had to hit "forget" on a couple of thousand notes.
The heatmap now counts them as reviews, which kind of messes up the whole look of it.
Is there a way of excluding "forgetting a card" in the review count?

![forgotten cards](https://user-images.githubusercontent.com/69243523/125193068-ed340a00-e24a-11eb-8398-21651322534a.png)

Thanks for all your amazing work!

**Comment by xflashkey** [comment]
I think that you should not exclude them, first at all, even if u forget the card u are reviewing it. You are seeing that card and re learning that card so it counts as a review.

**Comment by Spiralo-Idioide** [comment]
> I think that you should not exclude them, first at all, even if u forget the card u are reviewing it. You are seeing that card and re learning that card so it counts as a review.

Even though it might not be a good idea to forget cards, the option to do so exists, is used and the add-on don't take this into account even though it should.

I think it is necessary to have this functionnality.

**Comment by glutanimate** [comment]
Hey guys,

Thanks for the report! This should be fixed with v1.0.0 which I just released [on AnkiWeb](https://ankiweb.net/shared/info/1771074083 ) (no need for a manual installation any more, you can just copy the add-on code into Anki as with other add-ons.)

Basically, you can now configure whether the add-on takes rescheduled/forgotten cards into account or not (the default being that they aren't counted as repetitions). The setting can be found in the *Fine Tuning* tab in Review Heatmap's options.

Hope that helps! And if you run into any issues please do let me know.
