### ISSUE TITLE
Option to exclude certain decks from heatmap and stats

### ISSUE THREAD

**Issue by TimotheeChauvin** [glutanimate/review-heatmap#13]
Hi Aristotelis, thanks for this great add-on!
I'm using the [incremental reading add-on](https://github.com/luoliyan/incremental-reading) (specifically [this version](https://github.com/TimotheeChauvin/incremental-reading), actually), and I would like the review heatmap to only concern my non-IR deck (since reading a portion of an article doesn't count as a review in my opinion).
Perhaps other users also have 'special' decks (such as test decks, for example).
This is obviously going to concern few users, but I also think implementing it must be rather fast.
What do you think about it?

**Comment by glutanimate** [comment]
Hi Timothee,

thanks for the suggestion! Although this is not something I would use myself, I could see how an option like that might come in handy, so I've added it as a possible enhancement for the future.

Sadly I won't be able to work on this anytime soon due to time constraints and other projects taking precedence, but if someone decides to file a PR that implements this, I'd be more than happy to merge it.

(If this feature is very crucial to your workflow and something you would like to have available ASAP, I'd also be open to working on it on a commission basis. In that case please feel free to send me an email.)

**Comment by glutanimate** [comment]
Implemented with cbe80c56b0242929b748e43017b0632afa256b6b
