### ISSUE TITLE
Set due date cards being counted as reviewed. 

### ISSUE THREAD

**Issue by PHZCosta** [glutanimate/review-heatmap#138]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

I've noticed that if I set the due date to a certain card, it counts in the map as a review. I noticed today because I moved forward a bunch of cards (gotta enjoy Christmas) and my review heatmap was indicating a very high card count. I tested it a bit more and confirmed that every time I set the due date of a card, it increased the review count.

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by schattennarr** [comment]
Is there a workaround or a way to fix it?

**Comment by glutanimate** [comment]
Hey guys,

Thanks for the report! This should be fixed with v1.0.0 which I just released [on AnkiWeb](https://ankiweb.net/shared/info/1771074083 ) (no need for a manual installation any more, you can just copy the add-on code into Anki as with other add-ons.)

If you run into any issues please do let me know!
