### ISSUE TITLE
Thanks for the report, guys. It looks like this is a new feature in Anki 2.1.41. Will look into it, but as 2.1.41 broke a lot of add-ons, it might take me a bit of time to get to this.

### ISSUE THREAD

**Issue by cwmschmidty** [glutanimate/review-heatmap#141]
Thanks for the report, guys. It looks like this is a new feature in Anki 2.1.41. Will look into it, but as 2.1.41 broke a lot of add-ons, it might take me a bit of time to get to this.

_Originally posted by @glutanimate in https://github.com/glutanimate/review-heatmap/issues/108#issuecomment-805234458_

Has there been any new developments with this bug?

**Comment by glutanimate** [comment]
Hey [cwmschmidty](https://github.com/cwmschmidty),

This should be fixed with v1.0.0 which I just released [on AnkiWeb](https://ankiweb.net/shared/info/1771074083) (no need for a manual installation any more, you can just copy the add-on code into Anki as with other add-ons.).

Whether reschedules are included in the heatmap and stats is now configurable via an option under the "Fine Tuning" tab in the add-on's settings menu. It should be enabled by default, so if you had any overly high repetition counts due to manually forgetting/rescheduling cards, they should be corrected for those days

If you run into any issues please do let me know!

(cf #108)
