### ISSUE TITLE
Streak lost 

### ISSUE THREAD

**Issue by smiiletoday** [Glutanimate/review-heatmap#180]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
My anki synced and for some reason it reset all the cards that I did today and then it got rid of my cards that I did over the last two days and now my streak is gonr

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [X] I've restarted Anki to see if it helps
 - [X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [X] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [X] I've tried to disable other add-ons to see if there are any interactions present
 - [X] My issue disappears when I hold shift while starting Anki.
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi there, sorry to hear that! That sounds like a sync conflict issue, where syncing with AnkiWeb might have overwritten your local progress. Since this is something handled by Anki itself, I'm afraid there's not much the add-on can do here. My suggestion would be to look into whether you can perhaps restore from an [automatic backup](https://docs.ankiweb.net/backups.html#automatic-backups). But I would highly recommend that you create a [manual backup of your current collection](https://docs.ankiweb.net/backups.html#manual-colpkg-backups) before trying to restore an earlier backup.

If you need help with the backup & restoration process and/or if this doesn't work, I would recommend posting a support thread on the [Anki forums](https://forums.ankiweb.net/). The folks over there are usually very friendly and might be able to provide additional guidance.

Hope that helps for now!
