### ISSUE TITLE
Issue Report: if daily review is over 1K, the daily cube reads "NaN Review"

### ISSUE THREAD

**Issue by lizvoila** [Glutanimate/review-heatmap#3]
First of all, just wanna say thank you so much for this add-on. Have recommended my friends/anki users to use it.
This issue content is as the title states, once the daily review number is over 1K, the cube says "NaN reviews on ...." It's not a bug per se, because once it shows I will know it's over 1K, but much will be appreciated  if this could be fixed. Again, this is an amazing add-on and must have for every anki-user. 
Thanks again

Ps, I have three cubes like this. Done some binge-Anking for my backlogged cards. facepalm.jpg

**Comment by Glutanimate** [comment]
Hi lizvoila,

glad you like the add-on. 1K reviews is quite an impressive achievement, indeed! I think the most I reached on pre-exam days was around 700. No wonder I never noticed this issue! So thanks for the report.

In any case, this should be fixed with the latest commit. I will push a new release to AnkiWeb soon.

**Comment by lizvoila** [comment]
Thank you for fixing this issue.It works now and I've just hit 1K two days
in a row(Almost hit 2K, really tempted to see whether the reading would
work but too tired to go on). Binge-learning German/ reviewing Kindle vocab
takes up most of my free time and your add-on updates are really helpful to
keep track of my tags and daily progress
. Thanks again and look forward to more of your good coding work.

LI

2017-01-15 12:57 GMT+08:00 Aristotelis <notifications@github.com>:
