### ISSUE TITLE
some API for the outer reminder programm (streaks related).

### ISSUE THREAD

**Issue by JulyMorning** [glutanimate/review-heatmap#8]
I'm interested if there some way to make a simple API, so we could write an outer program working silently in system tray. it could check for these streaks and remind user to continue his memorization process.

**Comment by glutanimate** [comment]
Tbh, that would probably be best implemented as a separate add-on. Since Review Heatmap just parses Anki's review log, the systray app would just have to work with the same data. In terms of implementation details, you should be able to do this just with an Anki add-on. An external app should not be necessary.

It's a nice idea, though!
