### ISSUE TITLE
Anki process remains alive when window is closed.

### ISSUE THREAD

**Issue by toonswyzen** [glutanimate/review-heatmap#85]
#### Problem description

*After installing this add-on, once I close Anki and reopen, Anki remains 'running' and I cannot run Anki before it is killed. This issue is only present with this add-on enabled.*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    Anki 2.1.26 (70784154) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
    Platform: Linux
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-07-27 10:32:05
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Review Heatmap ['review_heatmap', 2020-04-30T15:23, 'None', '']
    Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2020-07-23T12:25, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1781298089
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi toonswyzen,

Thanks for taking the time to file a report!

Hmm, this is a bit of a weird one. Review Heatmap does not launch any background processes that could be blocking Anki from closing down, so if this is RH, it's an incredibly strange interaction. The add-on basically just uses all the bits and pieces that are already there and just injects the heatmap into some views, so I'd be really surprised if it somehow managed to cause this (especially given how long this version has been in use and by how many users, and how this is the first time I encounter an issue like this).

Before we dive into this further: Especially when an issue is intermittent, it can be very difficult to accurately ascribe it to a specific add-on. So I have to ask: How reliably can you reproduce the issue – and then once again resolve it – by enabling / disabling RH? Say you go through that cycle 3 times: Enable RH, see the issue, disable RH, issue is gone. Does it always appear when RH is active and disappear when RH is inactive?

If so, could you try completely uninstalling RH for a few days and then see if you run into this issue at all?

I don't want to take up too much of your time with troubleshooting, but since – if this is an issue with RH – it would be very difficult to track down, I think it's important to make 100% sure that it actually is caused by RH.

From my experience issues with Anki hanging are usually caused by two things:

1. Some kind of problem with the audio backend where the audio player (mpv or mplayer) will remain silently running in the background, thus preventing Anki from stopping.
2. An issue with background syncing where the sync process will hold up Anki.

I also see that you have the "Searching PDF Reading  Note-Taking in Add Dialog" add-in installed. It's disabled in the debug log, but if this was active when you experienced the problem, it's a much more likely candidate for the bug. "Searching" launches a background thread to build your card index, and a thread like this could theoretically hold Anki's process up.

Either way, let's gather some more info and then see if we can dive into this further.

**Comment by toonswyzen** [comment]
Hi @glutanimate, thanks for the quick response! I've been doing some more debugging and seems that the issue is indeed, not with the add-on. I've yet to find the issue, but I assume it's an issue with Anki on Linux. 

My apologies for the misconception!
